# Generated by Django 5.1.3 on 2024-12-04 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='stock',
            new_name='price',
        ),
    ]
