# Generated by Django 5.1.3 on 2024-12-05 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_itemphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemphoto',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='main.item'),
        ),
    ]
