# Generated by Django 5.1.3 on 2025-01-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_itemphoto_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_img/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='itemphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
