# Generated by Django 5.1.3 on 2025-01-13 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_itemphoto_thumbnail_img_alter_item_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='image',
        ),
    ]
